name: Build CI

on:
  push:
    branches: ["master"]

jobs:
  build-w32:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Install Deps
        uses: msys2/setup-msys2@v2.21.0
        with:
          update: true
          install: >-
            git
            autotools
            make
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-curl
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Pre Configure
        run: autoreconf --install
      - name: Configure
        run: ./configure
      - name: Make
        run: make -j4
      - name: Run Tests
        run: make check

  build-gnu:
    runs-on: ubuntu-latest

    steps: 
      - name: Install Deps
        uses: awalsh128/cache-apt-pkgs-action@v1.3.1
        with:
          packages: gcc-13 g++-13 make libcurl4-openssl-dev
          version: 2.0
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Pre Configure
        run: autoreconf --install
      - name: Configure
        run: ./configure CC=gcc-13 CPP=g++-13 CXX=g++-13 LD=g++-13
      - name: Make
        run: make -j4
      - name: Run Tests
        run: make check

  build-osx:
    runs-on: macos-latest
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - name: Install Deps
        uses: ConorMacBride/install-package@v1
        with:
          brew: automake autoconf 
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Pre Configure
        run: autoreconf --install
      - name: Configure
        run: ./configure
      - name: Make
        run: make -j3
      - name: Run Tests
        run: make check
        