name: Check Code Formatting

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  clang-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Clang Format Github Action
        uses: RafikFarhad/clang-format-github-action@v3
        with:
          style: "file"
          sources: "inc/utils/**/*.hh,src/core/**/*.cc,src/extra/**/*.cc,src/uic/*.cc,src/util/*.cc,src/Main.cc"
          